### PR TITLE
Limited Python 2 Support (#105)

### PR DESCRIPTION
**Pull request by mosminerCP**
Per Issue #105 adding limited Python2 support.

To be clear, we are not supporting the msgtools suite of applications on Python2.  Rather we are enabling users to use generated code on Python 2 and 3.  I added details and sample code on [the wiki](https://github.com/MilesEngineering/MsgTools/wiki/Python2-Support).  

Changes:
- A command line option for _msgparser_ to override the default messaging module so you can use your own.
- A sample Python2 enabled messaging module (_utils/python2/messaging.py_) that has been tested for message import, registration, and creation, i.e. the key functionality generated code requires.  Also tested the toJson method.  The balance of functionality is **untested**.
- Added _python_requires_ to _setup.py_ file.  Msgtools will only install on Python 3.5 and higher now. 
- Add \_\_init\_\_.py to each directory in the generated output to make Python2 imports happy.  
- Fixed a bug in _messaging.Messaging()_ for the _loaddir_ argument.  loadDir was not being initialized and raising an exception.
- Added missing _@staticmethod__ decorators on messaging module classes so functions can be used from the class directly, and instances of the class.
- Changed Messaging to use importlib.import_module to load message code.  This is the recommended method for programmatic import.  The builtin import only returns the top level package.
- Added a new Messaging.MsgClass utility method that lets you retrieve a message's class from a header (lookup by ID)
- Added an optional name parameter to MsgFactory so you can create messages by name now as well as a full message buffer.  Semantics are a little weird to preserve backward compatibility.
- Modified msgparser to delete generated code files if they are empty.  YAML files can define common YAML constructs included by other YAML files.  The common YAML files yield no generated code.  Empty files were causing some concern that an error occurred so cleaning them up.
- Added a set of _classifiers__ and _keywords_ to _setup.py_ to up our advertising game on PyPi.
- Documentation cleanup.

### CODE REVIEW

**Comment by mosminerCP** [comment]
@mgazic I'm going to hold off merging this in until you're comfortable this is the right path.  I'm happy to back out the new command line option etc.  

Also - please look closely at the changes I made to the LoadDir method on the msgtools/lib Messaging class.  To make it Python 2 friendly I dropped the importlib reference and switched to the __import__ form.  I believe this is functionally equivalent to what you had before, and similar to how you load the header in the constructor.   I'm not 100% confident though, as it looked like you chose importlib for a specific reason.

**Comment by mgazic** [comment]
> dropped the importlib reference and switched to the import form
I had complicated recursive-loading, and if we switch to import with __init__.py files in place in each directory, I wonder if we can just do one import statement to import the whole thing like a python package?

**Comment by mosminerCP** [comment]
Hmm..I confess the import system is still somewhat mysterious to me.  I like where your head is at though.  Let me go read up, and run a couple of experiments and see what I find out. 

I can say that as far as I can tell, the \__import__ method I've used here works fine with msgscope, server, and my test client program (under Python 2 and 3).  Doesn't mean there isn't some nuance though.

**Comment by mosminerCP** [comment]
I didn't read every last detail of the import documentation, but I've read enough that I feel confident enough to offer some thoughts.  First this method _importlib.machinery.SourceFileLoader(name, filepath).load_module(name)_ being used in the master right now was deprecated in Python 3.6.  exec_module() is the new form.  

That said, the current code is invoking a lower level loader that is normally handled by the top level import keyword.  I think we should try to use the top level import mechanisms so that we don't interfere with users who want to extend the import infrastructure in their apps.  If there is ever reason we need to override default Python importing we should do so via the standard import hooks.

With that goal, we should be using _importlib.import_module()_ to programatically load message modules according to Python's documentation.  Conveniently Python2 provides this method for backward compatibility so should be able to write the same code for both, and I'll make this change.

_importlib.import_module()_ is technically a simplifying wrapper around builtin.\__import__().  The key difference is builtin.\__import__() returns a reference to the top level package i.e. pkg of pkg.mod, instead of the module itself i.e. pkg.mod.  I'd think my use of it right now would cause all kinds of errors, but somehow it's magically working.  Inferring I'm still missing some nuance of package vs. module in this context.

For fun, a crazy idea comes to mind after reading all of this.  It would be technically possible to write an importer extension that generates Python code at the time of import.  Obviating the need for a command line msgparser tool for Python code.  Python's module cache takes precedence so you should only generate once.  Of course you'll probably want to add some initialization code to invalidate the cache if your YAML files have been updated too.

I'll switch us over to load_module() before we move to master here.

**Comment by mosminerCP** [comment]
@mgazic Any other changes you'd like to see?

**Comment by mgazic** [comment]
> @mgazic Any other changes you'd like to see?

None, unless you want to switch to importing all the generated code with one 'load_module', in this branch.

**Comment by mosminerCP** [comment]
This can be done.  Reading up a bit, I believe the correct equivalent approach would be to add imports for all modules in the package to \_\_init\_\_.py.  By simply importing a package you would implicitly import all the modules in that package.  We'll need to add imports for child packages in the parent \_\_init\_\_.py file to get the recursive import behavior we have now as well.

Thinking bigger, I believe the end goal with the existing recursion is to import all the message modules such that they register themselves with Messaging.  That enables all the handy utility methods it provides.   A couple of things about the current implementation (at least with respect to Python):

- Generated message code is tightly coupled to Messaging.  Some applications may just want to use the message code directly and forego all the utility methods Messaging provides.
- By importing everything on startup we're burning CPU and memory on imports that may never used.  Not a big deal for desktop environments, but for an embedded target we might care.

What if:
- We remove the Messaging references in the templates.  Making the message modules 100% standalone.
- Generate a top level \_\_init\_\_.py that registers all the messages by name, and ID, with a reference module name.  This same top level \_\_init\_\_.py can skip this step if the user doesn't provide a messaging library (i.e. ModuleNotFound exception)
- Make the Messaging class a lazy loader through the factory methods.

Out of that we get Python2 support since the current message code is good for Python2 already.  We also simplify the templates (at the expense of a more complex \_\_init\_\_\.py).  

I'd probably start by writing a  unit test for the Messaging class.  It's used by almost every tool as you well know.  We want to be sure we don't break everything!  We'll probably have to move all the tools to use factory methods to get message classes and instances instead of the underlying data structures directly too.

Thoughts?  If this seems good, I'm tempted to merge in this pull request and create a new refactoring enhancement for Messaging.

**Comment by mgazic** [comment]
Definitely merge this now, and we'll worry about the more complicated thing in the future.

>     * Generated message code is tightly coupled to Messaging.  Some applications may just want to use the message code directly and forego all the utility methods Messaging provides.
True, but we'd have to ditch the decorators, FieldInfo/BitfieldInfo, and call to Register.  If someone really didn't want that, maybe there should be a separate "lite" version of the template that leaves those out.

>     * By importing everything on startup we're burning CPU and memory on imports that may never used.  Not a big deal for desktop environments, but for an embedded target we might care.
True!

>     * We remove the Messaging references in the templates.  Making the message modules 100% standalone.
They still need FieldInfo/BitfieldInfo to be defined.  I guess we could change those to be nested dictionaries instead of objects....

>     * Make the Messaging class a lazy loader through the factory methods.
Would that still work for things like scope/inspector/JSON->msg/CSV->msg that want to be able to iterate over all defined messages?  If so, then it seems fine perhaps.  Would it prevent errors in generated python that are currently caught on heavy startup from being seen until they are lazily loaded?

> Out of that we get Python2 support since the current message code is good for Python2 already. We also simplify the templates (at the expense of a more complex __init__.py).

> We'll probably have to move all the tools to use factory methods to get message classes and instances instead of the underlying data structures directly too.
Can you elaborate on that?  I really like being able to get message classes by Messaging.Messages.AudioManagement.BlahBlah, I don't want to have to call what looks like a function with a string argument (Messaging.GetMessage("AudioManagement.BlahBlah")).

> Thoughts? If this seems good, I'm tempted to merge in this pull request and create a new refactoring enhancement for Messaging.
Sounds like a good plan!

**Comment by mosminerCP** [comment]
Let me see if I can figure out a way to support the decorators etc.  Meantime I'll merge this one in and open a new enhancement ticket to keep tabs on the Messaging ideas.

**Pull request merged**
