### PR TITLE
Fix for Windows Cygwin systems that show __main__.py inside of execut…

### PR DESCRIPTION
**Pull request by Prakash-Manandhar-Bose**
…able file in inspect.getfile

### CODE REVIEW

**Comment by mgazic** [comment]
> What am I missing?
A long time ago I had makefile-style dependency checking so that autogenerated code would get rebuilt if any of the source code of msgparser, MsgUtils.py or language plugins changed.  That got largely removed when I first made msgtools a pip package, and I think this is a remnant of it that got crippled but is still hanging around.

Matt, if you want to just yank out the remnants of the dead code (and test for regression with 'make test', or building for Bose), that would be excellent!

**Comment by Prakash-Manandhar-Bose** [comment]
I agree this is likely dead code and the whole block can be removed.

**Comment by mosminerCP** [comment]
Ok.  I'll just pile this onto my other pull request for Python2 since we're not making a functional change here.

**Comment by mosminerCP** [comment]
I removed the dead code, which also removes the need for this change.  Closing.

**Pull request closed without merging**
